#!/bin/sh
run_dir="$(dirname "$0")"
cd "$run_dir"
export LD_LIBRARY_PATH="../commons-library"
CONFIG_FILE=$1
TEST_FLAG=$2
valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./instance ${CONFIG_FILE:-instance.conf} ${TEST_FLAG:-}
