#!/bin/bash
if [[ -f "/usr/lib/libparsi.so" || -f "/usr/include/libparsi.so" ]]; then
	echo "Biblioteca ParSI ya instalada"
	exit 0
fi

cd /tmp
if [ -d "parsi" ]; then
	rm -rf parsi
fi
echo "Descargando ParSI..."
git clone https://github.com/sisoputnfrba/parsi.git
#mkdir parsi
if [ -d "parsi" ]; then
	echo "Instalando ParSI..."
	cd parsi
	sudo make install
	#touch libparsi.so
	#sudo mv libparsi.so /usr/lib/libparsi.so
	if [[ -f "/usr/lib/libparsi.so" || -f "/usr/include/libparsi.so" ]]; then
		echo "Biblioteca ParSI instalada correctamente"
	else
		echo "Error instalando biblioteca ParSI"
	fi
else
	echo "Error descargando ParSI"
	exit 1
fi
